### PR TITLE
Rewrite from scratch including v2

### PR DESCRIPTION
**Pull request by ewilly**
## Problem

- Make it work

## Solution

- Complete rewrite including move to packaging v2

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ewilly** [comment]
!testme

**Comment by ewilly** [comment]
!testme

**Comment by ewilly** [comment]
@Limezy @ericgaspar CI test is 100% passing and tests on my server side are passing too.
So could be merged.
Additionally could you give me admin rights to that repo ?
PS : The app is voluntary not update to the last one published in order to test the autoupdater script.

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
Wow thanks for the awesome work !
May I add you as the official package maintainer ? I run a last test and will merge afterwards

**Comment by Limezy** [comment]
I was too quick, the PR should have pointed to the testing branch...

**Comment by Limezy** [comment]
@ewilly you are now admin of this repo 😎

**Pull request merged**
