### PR TITLE
Testing - simplification

### PR DESCRIPTION
**Pull request by Salamandar**
* toml styling
* Simplify retrieval of manifest.toml info

@ewilly Is there a real reason why you manually install postgresql-v16 ?

### CODE REVIEW

**Comment by Salamandar** [comment]
!testme

**Comment by ewilly** [comment]
> @ewilly Is there a real reason why you manually install postgresql-v16 ?

pgvector is required and is not in bullseye (nor bookworm) but will come with trixie => due to pgvector we need to use the postgresl repo for now.
V15 works too, the current dockercompose use v14 and trixie will come with v16 which is the current stable version according to postgresql website => so i go to V16 directly (i didn't test V14 or V13 from postegresql repo)

**Comment by ewilly** [comment]
!testme

**Comment by ewilly** [comment]
!testme

**Comment by ewilly** [comment]
!testme

**Comment by ewilly** [comment]
!testme

**Comment by Salamandar** [comment]
Also: I can confirm this branch runs fine on my server (at least commit af79). I just don't have any face detection/recognition working, but that's unrelated.

**Pull request merged**
